/**
 * OverCMS Docker Compose installer
 *
 * Each OverCMS instance is cloned into /opt/overcms-sites/<domain>/app
 * and gets a unique set of ports so multiple installs can coexist.
 */

import { run } from './shell.js'
import { randomBytes } from 'crypto'
import { exec } from 'child_process'
import { promisify } from 'util'

const execAsync = promisify(exec)

const OVERCMS_REPO = 'https://github.com/jurfader/overCMS.git'
const OVERCMS_BASE_DIR = '/opt/overcms-sites'

function generatePassword(len = 24): string {
  return randomBytes(len).toString('base64url').slice(0, len)
}

/** Run a shell command with a custom timeout (ms). */
async function runLong(command: string, timeout = 600_000): Promise<{ stdout: string; stderr: string }> {
  try {
    return await execAsync(command, { timeout })
  } catch (err: any) {
    throw new Error(`Command failed: ${command}\n${err.stderr ?? err.message}`)
  }
}

// Get next available port range (each OverCMS install needs ~8 ports)
async function getNextPortBase(): Promise<number> {
  // Start at 10000, each install uses 10 ports (with padding)
  const { stdout } = await run(`ls ${OVERCMS_BASE_DIR} 2>/dev/null | wc -l`).catch(() => ({ stdout: '0', stderr: '' }))
  const count = parseInt(stdout.trim()) || 0
  return 10000 + (count * 10)
}

export interface OverCmsInstallOptions {
  domain: string
  adminEmail: string
  adminPassword: string
  licenseKey?: string
  ghToken?: string // for private repo access
}

export async function installOverCms(options: OverCmsInstallOptions): Promise<{
  apiUrl: string
  adminUrl: string
  apiPort: number
  adminPort: number
}> {
  const { domain, adminEmail, adminPassword, licenseKey, ghToken } = options
  const safeDomain = domain.replace(/[^a-z0-9.-]/g, '')
  const installDir = `${OVERCMS_BASE_DIR}/${safeDomain}`
  const portBase = await getNextPortBase()

  const apiPort = portBase
  const adminPort = portBase + 1
  const licensePort = portBase + 2
  const portalPort = portBase + 4
  const pgPort = portBase + 5
  const redisPort = portBase + 6
  const minioPort = portBase + 7

  const pgPassword = generatePassword()
  const redisPassword = generatePassword()
  const minioPassword = generatePassword()
  const authSecret = generatePassword(64)
  const licenseAdminSecret = generatePassword(32)

  const containerPrefix = safeDomain.replace(/\./g, '-')

  // 1. Create directory
  await run(`mkdir -p ${installDir}`)

  // 2. Clone repo
  const cloneUrl = ghToken
    ? `https://${ghToken}@github.com/jurfader/overCMS.git`
    : OVERCMS_REPO

  await run(`git clone ${cloneUrl} ${installDir}/app`)

  // 3. Generate .env
  const envContent = `
# OverCMS — Generated by OVERPANEL
# Domain: ${domain}

# Database
DATABASE_URL=postgresql://overcms:${pgPassword}@overcms-pg-${containerPrefix}:5432/overcms
POSTGRES_USER=overcms
POSTGRES_PASSWORD=${pgPassword}
POSTGRES_DB=overcms

# Redis
REDIS_URL=redis://overcms-redis-${containerPrefix}:6379
REDIS_PASSWORD=${redisPassword}

# S3 / MinIO
S3_ENDPOINT=http://overcms-minio-${containerPrefix}:9000
S3_REGION=auto
S3_ACCESS_KEY_ID=overcms-minio
S3_SECRET_ACCESS_KEY=${minioPassword}
S3_BUCKET=overcms
S3_PUBLIC_URL=https://${domain}/storage

# API
API_PORT=3000
API_URL=http://localhost:${apiPort}
API_DOMAIN=${domain}
BETTER_AUTH_SECRET=${authSecret}
BETTER_AUTH_URL=http://localhost:${apiPort}
ADMIN_CORS_ORIGINS=https://admin.${domain},http://localhost:${adminPort}

# Admin
ADMIN_DOMAIN=admin.${domain}
NEXT_PUBLIC_API_URL=https://${domain}/api

# License
LICENSE_PORT=3002
LICENSE_SERVER_URL=http://overcms-license-${containerPrefix}:3002
LICENSE_ADMIN_SECRET=${licenseAdminSecret}
LICENSE_DOMAIN=license.${domain}
OVERCMS_LICENSE_KEY=${licenseKey || ''}
OVERCMS_INSTALL_ID=${randomBytes(16).toString('hex')}
SITE_URL=https://${domain}

# Portal
PORTAL_DOMAIN=${domain}

# SSL
ACME_EMAIL=${adminEmail}
`.trim()

  await run(`cat > ${installDir}/app/.env << 'ENVEOF'
${envContent}
ENVEOF`)

  // 4. Create custom docker-compose.override.yml (no Traefik, expose ports directly)
  const composeOverride = `
version: "3.8"
services:
  postgres:
    container_name: overcms-pg-${containerPrefix}
    ports:
      - "${pgPort}:5432"
  redis:
    container_name: overcms-redis-${containerPrefix}
    ports:
      - "${redisPort}:6379"
  minio:
    container_name: overcms-minio-${containerPrefix}
    ports:
      - "${minioPort}:9000"
  api:
    container_name: overcms-api-${containerPrefix}
    ports:
      - "${apiPort}:3000"
  admin:
    container_name: overcms-admin-${containerPrefix}
    ports:
      - "${adminPort}:3001"
  license-server:
    container_name: overcms-license-${containerPrefix}
    ports:
      - "${licensePort}:3002"
  portal:
    container_name: overcms-portal-${containerPrefix}
    ports:
      - "${portalPort}:3004"
  traefik:
    profiles: ["disabled"]
`.trim()

  await run(`cat > ${installDir}/app/docker-compose.override.yml << 'COMPEOF'
${composeOverride}
COMPEOF`)

  // 5. Build and start containers (long timeout — Docker builds are slow)
  await runLong(`cd ${installDir}/app && docker compose -f docker-compose.prod.yml -f docker-compose.override.yml up -d --build`, 600_000)

  // 6. Wait for services to be ready
  await new Promise(r => setTimeout(r, 15000))

  // 7. Run database migration and seed
  await runLong(`cd ${installDir}/app && docker compose -f docker-compose.prod.yml -f docker-compose.override.yml exec -T api npx drizzle-kit push`).catch(() => {})
  await runLong(`cd ${installDir}/app && docker compose -f docker-compose.prod.yml -f docker-compose.override.yml exec -T api npx tsx packages/core/src/db/seed.ts`).catch(() => {})

  // 8. Store port mapping
  await run(`cat > ${installDir}/ports.json << 'EOF'
{"apiPort":${apiPort},"adminPort":${adminPort},"licensePort":${licensePort},"portalPort":${portalPort},"pgPort":${pgPort},"redisPort":${redisPort},"minioPort":${minioPort}}
EOF`)

  return {
    apiUrl: `http://localhost:${apiPort}`,
    adminUrl: `http://localhost:${adminPort}`,
    apiPort,
    adminPort,
  }
}

export async function uninstallOverCms(domain: string): Promise<void> {
  const safeDomain = domain.replace(/[^a-z0-9.-]/g, '')
  const installDir = `${OVERCMS_BASE_DIR}/${safeDomain}`

  // Stop and remove containers
  await runLong(`cd ${installDir}/app && docker compose -f docker-compose.prod.yml -f docker-compose.override.yml down -v 2>/dev/null || true`)

  // Remove directory
  await run(`rm -rf ${installDir}`)
}

export async function isOverCmsRunning(domain: string): Promise<boolean> {
  const safeDomain = domain.replace(/[^a-z0-9.-]/g, '')
  const containerName = `overcms-api-${safeDomain.replace(/\./g, '-')}`
  try {
    const { stdout } = await run(`docker inspect -f '{{.State.Running}}' ${containerName} 2>/dev/null`)
    return stdout.trim() === 'true'
  } catch {
    return false
  }
}
